/* Outreach teams imported from the Lovable "Outreach Metrics Hub" on 2026-09-20 —
   YWAM Siem Reap's team records up to then, so the Teams page opens with its
   history rather than blank. api.js lays whatever has been saved since over
   these by id (getTeamTrips_): editing or deleting one here writes a row to
   the teamTrips blob, this file is never rewritten. Numbers: where the hub
   had week-by-week rows for a team those are summed; otherwise the team's
   recorded totals are taken as they were. Several 2024–25 teams share
   identical totals (304/177/127/3896, 76/39/37/1639) — that is how the hub
   held them, they were not invented here; edit them in the app. */
export default [
 {
  "id": "lv_5c43edf9",
  "campus": "siemreap",
  "name": "YWAM Ships Kona",
  "org": "YWAM Ships Kona",
  "country": "United States",
  "from": "2024-10-20",
  "to": "2024-11-30",
  "size": 9,
  "males": null,
  "females": null,
  "couples": null,
  "families": null,
  "staff": "Trent & Sam",
  "focus": "Teaching, Evangelism",
  "status": "active",
  "metrics": {
   "People Served": 2435,
   "People Heard the Gospel": 0,
   "Community Service Hours": 210,
   "Salvations": 0,
   "Healings": 0
  },
  "reached": {
   "male": 953,
   "female": 1482
  },
  "notes": "",
  "src": "lovable",
  "updated": "2026-09-20T00:00:00.000Z"
 },
 {
  "id": "lv_cf50a2eb",
  "campus": "siemreap",
  "name": "YWAM Santa Cruz",
  "org": "YWAM Santa Cruz",
  "country": "United States",
  "from": "2024-12-09",
  "to": "2025-01-13",
  "size": 6,
  "males": null,
  "females": null,
  "couples": null,
  "families": null,
  "staff": "Shane, Sarah, Maddy",
  "focus": "Teaching, Evangelism",
  "status": "active",
  "metrics": {
   "People Served": 304,
   "People Heard the Gospel": 0,
   "Community Service Hours": 3896,
   "Salvations": 2,
   "Healings": 0
  },
  "reached": {
   "male": 127,
   "female": 177
  },
  "notes": "",
  "src": "lovable",
  "updated": "2026-09-20T00:00:00.000Z"
 },
 {
  "id": "lv_675a9e39",
  "campus": "siemreap",
  "name": "YWAM TJ",
  "org": "YWAM TJ",
  "country": "Mexico",
  "from": "2024-12-10",
  "to": "2024-12-23",
  "size": 11,
  "males": null,
  "females": null,
  "couples": null,
  "families": null,
  "staff": "Josue & Julia",
  "focus": "Teaching, Evangelism",
  "status": "active",
  "metrics": {
   "People Served": 302,
   "People Heard the Gospel": 0,
   "Community Service Hours": 3896,
   "Salvations": 2,
   "Healings": 0
  },
  "reached": {
   "male": 125,
   "female": 177
  },
  "notes": "",
  "src": "lovable",
  "updated": "2026-09-20T00:00:00.000Z"
 },
 {
  "id": "lv_1bd132d5",
  "campus": "siemreap",
  "name": "YWAM Honolulu",
  "org": "YWAM Honolulu",
  "country": "United States",
  "from": "2024-12-16",
  "to": "2025-01-03",
  "size": 12,
  "males": null,
  "females": null,
  "couples": null,
  "families": null,
  "staff": "Emma & Emmy",
  "focus": "Teaching, Evangelism",
  "status": "active",
  "metrics": {
   "People Served": 304,
   "People Heard the Gospel": 0,
   "Community Service Hours": 3896,
   "Salvations": 2,
   "Healings": 0
  },
  "reached": {
   "male": 127,
   "female": 177
  },
  "notes": "",
  "src": "lovable",
  "updated": "2026-09-20T00:00:00.000Z"
 },
 {
  "id": "lv_e75e5597",
  "campus": "siemreap",
  "name": "Crossroads Korea",
  "org": "YWAM Kona",
  "country": "United States",
  "from": "2024-12-26",
  "to": "2025-01-13",
  "size": 8,
  "males": null,
  "females": null,
  "couples": null,
  "families": null,
  "staff": "N/a",
  "focus": "Teaching, Evangelism",
  "status": "active",
  "metrics": {
   "People Served": 304,
   "People Heard the Gospel": 0,
   "Community Service Hours": 3896,
   "Salvations": 2,
   "Healings": 0
  },
  "reached": {
   "male": 127,
   "female": 177
  },
  "notes": "",
  "src": "lovable",
  "updated": "2026-09-20T00:00:00.000Z"
 },
 {
  "id": "lv_793c249d",
  "campus": "siemreap",
  "name": "YWAM EA",
  "org": "YWAM Experience Asia",
  "country": "Malaysia",
  "from": "2025-01-20",
  "to": "2025-02-10",
  "size": 1,
  "males": null,
  "females": null,
  "couples": null,
  "families": null,
  "staff": "Max, Josiah, Eli",
  "focus": "Teaching, Evangelism",
  "status": "active",
  "metrics": {
   "People Served": 76,
   "People Heard the Gospel": 88,
   "Community Service Hours": 1639,
   "Salvations": 4,
   "Healings": 2
  },
  "reached": {
   "male": 37,
   "female": 39
  },
  "notes": "",
  "src": "lovable",
  "updated": "2026-09-20T00:00:00.000Z"
 },
 {
  "id": "lv_c429a5c3",
  "campus": "siemreap",
  "name": "Living Water Church",
  "org": "Four Square",
  "country": "United States",
  "from": "2025-03-07",
  "to": "2025-03-15",
  "size": 25,
  "males": null,
  "females": null,
  "couples": null,
  "families": null,
  "staff": "JP",
  "focus": "Youth programs",
  "status": "active",
  "metrics": {
   "People Served": 76,
   "People Heard the Gospel": 88,
   "Community Service Hours": 1639,
   "Salvations": 4,
   "Healings": 2
  },
  "reached": {
   "male": 37,
   "female": 39
  },
  "notes": "",
  "src": "lovable",
  "updated": "2026-09-20T00:00:00.000Z"
 },
 {
  "id": "lv_5d1f1541",
  "campus": "siemreap",
  "name": "YWAM COS",
  "org": "YWAM Colorado Springs",
  "country": "United States",
  "from": "2025-03-27",
  "to": "2025-06-09",
  "size": 11,
  "males": null,
  "females": null,
  "couples": null,
  "families": null,
  "staff": "Markus & Makayla",
  "focus": "Evangelism, soccer, teaching english",
  "status": "active",
  "metrics": {
   "People Served": 76,
   "People Heard the Gospel": 88,
   "Community Service Hours": 1639,
   "Salvations": 4,
   "Healings": 2
  },
  "reached": {
   "male": 37,
   "female": 39
  },
  "notes": "",
  "src": "lovable",
  "updated": "2026-09-20T00:00:00.000Z"
 },
 {
  "id": "lv_c82233f5",
  "campus": "siemreap",
  "name": "Revival & Reformation",
  "org": "YWAM Kona",
  "country": "United States",
  "from": "2025-04-02",
  "to": "2025-04-29",
  "size": 15,
  "males": null,
  "females": null,
  "couples": null,
  "families": null,
  "staff": "Bethany",
  "focus": "Anti-human trafficking",
  "status": "active",
  "metrics": {
   "People Served": 76,
   "People Heard the Gospel": 88,
   "Community Service Hours": 1639,
   "Salvations": 4,
   "Healings": 2
  },
  "reached": {
   "male": 37,
   "female": 39
  },
  "notes": "",
  "src": "lovable",
  "updated": "2026-09-20T00:00:00.000Z"
 },
 {
  "id": "lv_b87b05c4",
  "campus": "siemreap",
  "name": "Ships January DTS",
  "org": "YWAM Ships Kona",
  "country": "United States",
  "from": "2025-04-03",
  "to": "2025-05-06",
  "size": 7,
  "males": null,
  "females": null,
  "couples": null,
  "families": null,
  "staff": "Jenna & Juda",
  "focus": "Evangelism",
  "status": "active",
  "metrics": {
   "People Served": 76,
   "People Heard the Gospel": 88,
   "Community Service Hours": 1639,
   "Salvations": 4,
   "Healings": 2
  },
  "reached": {
   "male": 37,
   "female": 39
  },
  "notes": "",
  "src": "lovable",
  "updated": "2026-09-20T00:00:00.000Z"
 },
 {
  "id": "lv_3652e33f",
  "campus": "siemreap",
  "name": "Restoring Relationship",
  "org": "YWAM Penang",
  "country": "Malaysia",
  "from": "2025-06-08",
  "to": "2025-06-21",
  "size": 6,
  "males": null,
  "females": null,
  "couples": null,
  "families": null,
  "staff": "Angelica",
  "focus": "Counseling",
  "status": "active",
  "metrics": {
   "People Served": 76,
   "People Heard the Gospel": 88,
   "Community Service Hours": 1639,
   "Salvations": 4,
   "Healings": 2
  },
  "reached": {
   "male": 37,
   "female": 39
  },
  "notes": "",
  "src": "lovable",
  "updated": "2026-09-20T00:00:00.000Z"
 },
 {
  "id": "lv_374ccf90",
  "campus": "siemreap",
  "name": "Rising DTS",
  "org": "YWAM Kona",
  "country": "United States",
  "from": "2025-07-27",
  "to": "2025-08-19",
  "size": 9,
  "males": null,
  "females": null,
  "couples": null,
  "families": null,
  "staff": "Min Young Lee & Sharon",
  "focus": "Evangelism",
  "status": "active",
  "metrics": {
   "People Served": 76,
   "People Heard the Gospel": 88,
   "Community Service Hours": 1639,
   "Salvations": 4,
   "Healings": 2
  },
  "reached": {
   "male": 37,
   "female": 39
  },
  "notes": "",
  "src": "lovable",
  "updated": "2026-09-20T00:00:00.000Z"
 },
 {
  "id": "lv_eff56fd0",
  "campus": "siemreap",
  "name": "YWAM Nha Trang",
  "org": "YWAM Vietnam",
  "country": "Vietnam",
  "from": "2025-11-23",
  "to": "2025-12-04",
  "size": 5,
  "males": null,
  "females": null,
  "couples": null,
  "families": null,
  "staff": "Hana & Joshua",
  "focus": "Teaching, Evangelism",
  "status": "active",
  "metrics": {
   "People Served": 76,
   "People Heard the Gospel": 88,
   "Community Service Hours": 1639,
   "Salvations": 4,
   "Healings": 2
  },
  "reached": {
   "male": 37,
   "female": 39
  },
  "notes": "",
  "src": "lovable",
  "updated": "2026-09-20T00:00:00.000Z"
 },
 {
  "id": "lv_1520c728",
  "campus": "siemreap",
  "name": "YWAM COS Q4 2025",
  "org": "YWAM Colorado Springs",
  "country": "United States",
  "from": "2025-12-10",
  "to": "2026-01-05",
  "size": 10,
  "males": null,
  "females": null,
  "couples": null,
  "families": null,
  "staff": "Domingos & Maddie",
  "focus": "Teaching, Evangelism",
  "status": "active",
  "metrics": {
   "People Served": 440,
   "People Heard the Gospel": 200,
   "Community Service Hours": 90,
   "Salvations": 1,
   "Healings": 2
  },
  "reached": {
   "male": 210,
   "female": 230
  },
  "notes": "",
  "src": "lovable",
  "updated": "2026-09-20T00:00:00.000Z"
 },
 {
  "id": "lv_7ea85f4f",
  "campus": "siemreap",
  "name": "YWAM Osaka",
  "org": "YWAM Japan",
  "country": "Japan",
  "from": "2025-12-12",
  "to": "2025-12-13",
  "size": 9,
  "males": null,
  "females": null,
  "couples": null,
  "families": null,
  "staff": "Isabela",
  "focus": "Debrief",
  "status": "active",
  "metrics": {
   "People Served": 76,
   "People Heard the Gospel": 88,
   "Community Service Hours": 1639,
   "Salvations": 4,
   "Healings": 2
  },
  "reached": {
   "male": 37,
   "female": 39
  },
  "notes": "",
  "src": "lovable",
  "updated": "2026-09-20T00:00:00.000Z"
 },
 {
  "id": "lv_e2d2209b",
  "campus": "siemreap",
  "name": "ACP Outreach Team",
  "org": "Antioch",
  "country": "Singapore",
  "from": "2025-12-13",
  "to": "2025-12-21",
  "size": 10,
  "males": null,
  "females": null,
  "couples": null,
  "families": null,
  "staff": "Danielle & Shaun",
  "focus": "Teaching, Evangelism",
  "status": "active",
  "metrics": {
   "People Served": 76,
   "People Heard the Gospel": 88,
   "Community Service Hours": 1639,
   "Salvations": 4,
   "Healings": 2
  },
  "reached": {
   "male": 37,
   "female": 39
  },
  "notes": "",
  "src": "lovable",
  "updated": "2026-09-20T00:00:00.000Z"
 },
 {
  "id": "lv_237cf381",
  "campus": "siemreap",
  "name": "Endeavor DTS",
  "org": "YWAM Kona",
  "country": "United States",
  "from": "2025-12-26",
  "to": "2026-01-18",
  "size": 10,
  "males": null,
  "females": null,
  "couples": null,
  "families": null,
  "staff": "Monique & Ben",
  "focus": "Teaching, Evangelism",
  "status": "active",
  "metrics": {
   "People Served": 600,
   "People Heard the Gospel": 200,
   "Community Service Hours": 90,
   "Salvations": 7,
   "Healings": 1
  },
  "reached": {
   "male": 300,
   "female": 300
  },
  "notes": "",
  "src": "lovable",
  "updated": "2026-09-20T00:00:00.000Z"
 },
 {
  "id": "lv_71b543be",
  "campus": "siemreap",
  "name": "Furnace DTS",
  "org": "YWAM New Zealand",
  "country": "New Zealand",
  "from": "2025-12-29",
  "to": "2026-01-28",
  "size": 11,
  "males": null,
  "females": null,
  "couples": null,
  "families": null,
  "staff": "Matthew & Shay",
  "focus": "Teaching, Evangelism",
  "status": "active",
  "metrics": {
   "People Served": 0,
   "People Heard the Gospel": 129,
   "Community Service Hours": 150,
   "Salvations": 3,
   "Healings": 1
  },
  "reached": {
   "male": 0,
   "female": 0
  },
  "notes": "",
  "src": "lovable",
  "updated": "2026-09-20T00:00:00.000Z"
 },
 {
  "id": "lv_b4e67a07",
  "campus": "siemreap",
  "name": "YWAM EA",
  "org": "YWAM EA",
  "country": "Malaysia",
  "from": "2026-01-13",
  "to": "2026-02-02",
  "size": 7,
  "males": null,
  "females": null,
  "couples": null,
  "families": null,
  "staff": "Christiana and Nehemiah",
  "focus": "Evangelism, school ministry",
  "status": "active",
  "metrics": {},
  "reached": {
   "male": null,
   "female": null
  },
  "notes": "",
  "src": "lovable",
  "updated": "2026-09-20T00:00:00.000Z"
 },
 {
  "id": "lv_6bdf1a87",
  "campus": "siemreap",
  "name": "Living Water Church Q1 2026",
  "org": "Four Square",
  "country": "United States",
  "from": "2026-01-23",
  "to": "2026-02-01",
  "size": 10,
  "males": null,
  "females": null,
  "couples": null,
  "families": null,
  "staff": "Pastor Jon",
  "focus": "Teaching, Evangelism",
  "status": "active",
  "metrics": {
   "People Served": 500,
   "People Heard the Gospel": 0,
   "Community Service Hours": 10,
   "Salvations": 10,
   "Healings": 0
  },
  "reached": {
   "male": 200,
   "female": 300
  },
  "notes": "",
  "src": "lovable",
  "updated": "2026-09-20T00:00:00.000Z"
 },
 {
  "id": "lv_9d28497a",
  "campus": "siemreap",
  "name": "Crossroads DTS",
  "org": "YWAM Kona",
  "country": "United States",
  "from": "2026-01-27",
  "to": "2026-02-16",
  "size": 8,
  "males": null,
  "females": null,
  "couples": null,
  "families": null,
  "staff": "Katrin",
  "focus": "Teaching, Evangelism",
  "status": "active",
  "metrics": {},
  "reached": {
   "male": null,
   "female": null
  },
  "notes": "",
  "src": "lovable",
  "updated": "2026-09-20T00:00:00.000Z"
 },
 {
  "id": "lv_736858cb",
  "campus": "siemreap",
  "name": "Cultivate DTS",
  "org": "YWAM Italy",
  "country": "Italy",
  "from": "2026-02-02",
  "to": "2026-02-26",
  "size": 7,
  "males": null,
  "females": null,
  "couples": null,
  "families": null,
  "staff": "Hannah & Maria",
  "focus": "Teaching, Evangelism",
  "status": "cancelled",
  "metrics": {},
  "reached": {
   "male": null,
   "female": null
  },
  "notes": "",
  "src": "lovable",
  "updated": "2026-09-20T00:00:00.000Z"
 },
 {
  "id": "lv_7cdc6bcb",
  "campus": "siemreap",
  "name": "YWAM Freiburg DTS",
  "org": "YWAM Germany",
  "country": "Germany",
  "from": "2026-02-08",
  "to": "2026-02-22",
  "size": 9,
  "males": null,
  "females": null,
  "couples": null,
  "families": null,
  "staff": "Gabriela",
  "focus": "Teaching, Evangelism",
  "status": "active",
  "metrics": {
   "People Served": 250,
   "People Heard the Gospel": 100,
   "Community Service Hours": 60,
   "Salvations": 0,
   "Healings": 0
  },
  "reached": {
   "male": 100,
   "female": 150
  },
  "notes": "",
  "src": "lovable",
  "updated": "2026-09-20T00:00:00.000Z"
 },
 {
  "id": "lv_86560151",
  "campus": "siemreap",
  "name": "YWAM Rogaland Family DTS",
  "org": "YWAM Norway",
  "country": "Norway",
  "from": "2026-02-23",
  "to": "2026-03-02",
  "size": 13,
  "males": null,
  "females": null,
  "couples": null,
  "families": null,
  "staff": "Catherine",
  "focus": "Teaching, Evangelism",
  "status": "active",
  "metrics": {},
  "reached": {
   "male": null,
   "female": null
  },
  "notes": "",
  "src": "lovable",
  "updated": "2026-09-20T00:00:00.000Z"
 },
 {
  "id": "lv_28e41b6b",
  "campus": "siemreap",
  "name": "Link students team",
  "org": "Link Bible School",
  "country": "Norway",
  "from": "2026-03-12",
  "to": "2026-03-25",
  "size": 13,
  "males": null,
  "females": null,
  "couples": null,
  "families": null,
  "staff": "Kenneth",
  "focus": "Teaching, Evangelism",
  "status": "active",
  "metrics": {},
  "reached": {
   "male": null,
   "female": null
  },
  "notes": "",
  "src": "lovable",
  "updated": "2026-09-20T00:00:00.000Z"
 },
 {
  "id": "lv_3c905d27",
  "campus": "siemreap",
  "name": "Cascades DTS",
  "org": "YWAM Cascades",
  "country": "USA",
  "from": "2026-03-31",
  "to": "2026-06-07",
  "size": 12,
  "males": null,
  "females": null,
  "couples": null,
  "families": null,
  "staff": "Dan, Andrew, Alyssa",
  "focus": "Teaching, Evangelism",
  "status": "active",
  "metrics": {},
  "reached": {
   "male": null,
   "female": null
  },
  "notes": "",
  "src": "lovable",
  "updated": "2026-09-20T00:00:00.000Z"
 },
 {
  "id": "lv_e2f4bef5",
  "campus": "siemreap",
  "name": "PHC Outreach Team",
  "org": "YWAM Perth",
  "country": "Australia",
  "from": "2026-03-31",
  "to": "2026-05-13",
  "size": 8,
  "males": null,
  "females": null,
  "couples": null,
  "families": null,
  "staff": "Joanna",
  "focus": "Medical",
  "status": "active",
  "metrics": {},
  "reached": {
   "male": null,
   "female": null
  },
  "notes": "",
  "src": "lovable",
  "updated": "2026-09-20T00:00:00.000Z"
 },
 {
  "id": "lv_81110c15",
  "campus": "siemreap",
  "name": "YWAM Seamill DTS",
  "org": "YWAM Seamill",
  "country": "Scotland",
  "from": "2026-05-04",
  "to": "2026-07-10",
  "size": 0,
  "males": null,
  "females": null,
  "couples": null,
  "families": null,
  "staff": "Simeon",
  "focus": "Evangelism",
  "status": "active",
  "metrics": {},
  "reached": {
   "male": null,
   "female": null
  },
  "notes": "",
  "src": "lovable",
  "updated": "2026-09-20T00:00:00.000Z"
 },
 {
  "id": "lv_db9cdeef",
  "campus": "siemreap",
  "name": "Multi-Gen DTS",
  "org": "YWAM Penang",
  "country": "Malaysia",
  "from": "2026-05-05",
  "to": "2026-05-22",
  "size": 0,
  "males": null,
  "females": null,
  "couples": null,
  "families": null,
  "staff": "Bervie",
  "focus": "Teaching, Evangelism",
  "status": "active",
  "metrics": {},
  "reached": {
   "male": null,
   "female": null
  },
  "notes": "",
  "src": "lovable",
  "updated": "2026-09-20T00:00:00.000Z"
 },
 {
  "id": "lv_b9ddfe2b",
  "campus": "siemreap",
  "name": "YWAM Furnace DTS",
  "org": "YWAM Furnace",
  "country": "New Zealand",
  "from": "2026-06-01",
  "to": "2026-06-17",
  "size": 0,
  "males": null,
  "females": null,
  "couples": null,
  "families": null,
  "staff": "Evan & Morgan",
  "focus": "Teaching, Evangelism",
  "status": "active",
  "metrics": {},
  "reached": {
   "male": null,
   "female": null
  },
  "notes": "",
  "src": "lovable",
  "updated": "2026-09-20T00:00:00.000Z"
 }
];
